# Construiește OscLazerRealmImport (dotnet) + OSC.exe (PyInstaller).
# Ieșire: dist\OSC\OSC.exe și dist\OSC\OscLazerRealmImport.exe
#
# Build-ul merge întâi în dist\_osc_build_staging\OSC\ ca să nu șteargă dist\OSC
# cât timp OSC.exe rulează (altfel WinError 5 pe _internal\*.dll).

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
Set-Location $root

# Marcaj vizibil în titlul ferestrei exe (verifici că rulezi build-ul tocmai făcut).
$stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$stampPy = Join-Path $root "osc_collector\_build_stamp.py"
Set-Content -Path $stampPy -Encoding utf8 -Value @(
  '# Auto-generated by build_exe.ps1 - do not edit.',
  "BUILD_STAMP = `"$stamp`""
)

$venvPyInstaller = Join-Path $root ".venv\Scripts\pyinstaller.exe"
if (-not (Test-Path $venvPyInstaller)) {
  Write-Error "Lipsește .venv. Rulează: python -m venv .venv; .\.venv\Scripts\pip install -r requirements-dev.txt"
}

$pub = Join-Path $root "tools\OscLazerRealmImport\publish-out"
dotnet test (Join-Path $root "tools\OscLazerRealmImport.Tests\OscLazerRealmImport.Tests.csproj") -c Release
if ($LASTEXITCODE -ne 0) {
  Write-Error "OscLazerRealmImport.Tests a eșuat; corectează înainte de publish."
}
# Self-contained: pe PC-ul destinatarului nu e nevoie de .NET Runtime instalat.
dotnet publish (Join-Path $root "tools\OscLazerRealmImport\OscLazerRealmImport.csproj") `
  -c Release -r win-x64 --self-contained true -o $pub

$realmExe = Join-Path $pub "OscLazerRealmImport.exe"
if (-not (Test-Path $realmExe)) {
  Write-Error "Nu s-a găsit $realmExe după dotnet publish."
}

$stageDist = Join-Path $root "dist\_osc_build_staging"
$stageWork = Join-Path $root "build\_osc_build_work"
if (Test-Path $stageDist) {
  Remove-Item $stageDist -Recurse -Force -ErrorAction SilentlyContinue
}
if (Test-Path $stageWork) {
  Remove-Item $stageWork -Recurse -Force -ErrorAction SilentlyContinue
}

& $venvPyInstaller --noconfirm `
  --distpath $stageDist `
  --workpath $stageWork `
  (Join-Path $root "OSC.spec")

$built = Join-Path $stageDist "OSC"
$builtExe = Join-Path $built "OSC.exe"
if (-not (Test-Path $builtExe)) {
  Write-Error "PyInstaller nu a produs $builtExe"
}

# Tot output-ul publish (exe, dll-uri native Realm, runtime .NET self-contained) lângă OSC.exe.
Copy-Item -Path (Join-Path $pub '*') -Destination $built -Recurse -Force

$final = Join-Path $root "dist\OSC"
$promoted = $false
try {
  if (Test-Path $final) {
    Remove-Item $final -Recurse -Force
  }
  Move-Item -LiteralPath $built -Destination $final
  $promoted = $true
} catch {
  Write-Warning "Nu pot înlocui dist\OSC (închide OSC.exe sau Explorer deschis în acel folder): $($_.Exception.Message)"
  if (Test-Path $final) {
    foreach ($item in Get-ChildItem -Path $pub -File) {
      $dst = Join-Path $final $item.Name
      try {
        Copy-Item -LiteralPath $item.FullName -Destination $dst -Force -ErrorAction Stop
      } catch {
        Write-Warning "Nu am putut copia $($item.Name): $($_.Exception.Message)"
      }
    }
    Write-Host ""
    Write-Host "Actualizare parțială: tot output-ul dotnet publish → dist\OSC (fișierele blocate de OSC.exe sar peste)."
    Write-Host "Pentru OSC.exe / UI nou (sidebar), închide aplicația și rulează din nou build_exe.ps1."
    Write-Host ""
  }
}

if ($promoted) {
  if (Test-Path $stageDist) {
    Remove-Item $stageDist -Recurse -Force -ErrorAction SilentlyContinue
  }
  Write-Host ""
  Write-Host "OK: dist\OSC\ — dublu-clic pe OSC.exe. Trimite întreg folderul OSC (zip); nu e nevoie de Python sau .NET pe PC-ul destinatarului."
  Write-Host "Note: dist\_osc_build_staging is removed after a successful build (folder is temporary)."
  Write-Host ""
} else {
  Write-Host ""
  Write-Host "New build folder (copy over dist\OSC after closing OSC.exe):"
  Write-Host "  $built"
  Write-Host ""
}
